# Generated by Django 2.2.12 on 2023-03-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('price', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.IntegerField(choices=[(1, 'Rank 1'), (2, 'Rank 2')], default=0)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Day off'), (2, 'At Work'), (3, 'Sickness'), (9, 'Fired')], default=1)),
                ('services', models.ManyToManyField(to='salon.Service')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(2, 'Accepted'), (3, 'Refused'), (9, 'Inactive')], default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Specialist')),
            ],
        ),
    ]
