# Generated by Django 2.2.12 on 2023-03-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='date',
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='begin_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
