# Generated by Django 2.2.12 on 2023-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20230331_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
