# Generated by Django 2.2.12 on 2023-04-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
